[build]
default-target = "x86_64-unknown-linux-musl"

[target.x86_64-unknown-linux-musl]
pre-build = ["apt-get update && apt-get install --assume-yes protobuf-compiler"]

[target.aarch64-unknown-linux-musl]
pre-build = ["apt-get update && apt-get install --assume-yes protobuf-compiler"]