[workspace.package]
version = "0.11.0"
edition = "2021"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/deislabs/containerd-wasm-shims"
homepage = "https://github.com/deislabs/containerd-wasm-shims"


[workspace]
resolver = "2"
members = [
    "tests"
]