[package]
name = "containerd-shim-spin-v1"
version = "0.5.1"
authors = ["DeisLabs Engineering Team"]
edition = "2021"
repository = 'https://github.com/deislabs/containerd-wasm-shims'
license = "Apache-2.0"
homepage = 'https://github.com/deislabs/containerd-wasm-shims'
description = """
Containerd shim for running Spin workloads.
"""

[dependencies]
chrono = "~0.4"
clap = { version = "4.1.9", features = ["derive", "env"] }
containerd-shim = "~0.3"
containerd-shim-wasm = "0.1.1"
log = "~0.4"
spin-trigger = { git = "https://github.com/fermyon/spin", rev = "2f50f3e5db61bc68339882f903a283e8bc82185c" }
spin-app = { git = "https://github.com/fermyon/spin", rev = "2f50f3e5db61bc68339882f903a283e8bc82185c" }
spin-core = { git = "https://github.com/fermyon/spin", rev = "2f50f3e5db61bc68339882f903a283e8bc82185c" }
spin-trigger-http = { git = "https://github.com/fermyon/spin", rev = "2f50f3e5db61bc68339882f903a283e8bc82185c" }
spin-loader = { git = "https://github.com/fermyon/spin", rev = "2f50f3e5db61bc68339882f903a283e8bc82185c" }
spin-manifest = { git = "https://github.com/fermyon/spin", rev = "2f50f3e5db61bc68339882f903a283e8bc82185c" }
wasmtime = "8.0.1"
tokio = { version = "1", features = ["rt"] }
tokio-util = { version = "0.7.7", features = ["codec"] }
openssl = { version = "*", features = ["vendored"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.82"
url = "2.2.2"
reqwest = { version = "0.11", features = ["stream"] }
anyhow = "1.0"
async-trait = "0.1"

[workspace]