[package]
name = "containerd-shim-spin-v1"
version = "0.9.1"
authors = ["DeisLabs Engineering Team"]
edition = "2021"
repository = 'https://github.com/deislabs/containerd-wasm-shims'
license = "Apache-2.0"
homepage = 'https://github.com/deislabs/containerd-wasm-shims'
description = """
Containerd shim for running Spin workloads.
"""

[dependencies]
chrono = "0.4"
clap = { version = "4.3", features = ["derive", "env"] }
containerd-shim = "0.5.0"
containerd-shim-wasm = { git = "https://github.com/containerd/runwasi", rev = "4d212b968d24d42a27952e8b04979382b543a613", features = ["cgroupsv2"] }
libcontainer = { git = "https://github.com/containers/youki", rev = "09e67372a892f22a89eeef62ff429c3cbcac6d41", features = ["v1","v2"], default-features = false }
log = "0.4"
spin-trigger = { git = "https://github.com/fermyon/spin", tag = "v1.4.1" }
spin-app = { git = "https://github.com/fermyon/spin", tag = "v1.4.1" }
spin-core = { git = "https://github.com/fermyon/spin", tag = "v1.4.1" }
spin-trigger-http = { git = "https://github.com/fermyon/spin", tag = "v1.4.1" }
spin-redis-engine = { git = "https://github.com/fermyon/spin", tag = "v1.4.1" }
spin-loader = { git = "https://github.com/fermyon/spin", tag = "v1.4.1" }
spin-manifest = { git = "https://github.com/fermyon/spin", tag = "v1.4.1" }
wasmtime = "10.0.1"
tokio = { version = "1", features = ["rt"] }
tokio-util = { version = "0.7", features = ["codec"] }
openssl = { version = "*", features = ["vendored"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
url = "2.3"
reqwest = { version = "0.11", features = ["stream"] }
anyhow = "1.0"
async-trait = "0.1"
oci-spec = "0.6.2"
libc = "0.2.147"
nix = "0.26.2"
utils = { path = "../utils" }

[workspace]
