[package]
name = "containerd-shim-wws-v1"
version = "0.9.0"
authors = ["Wasm Labs team <wasmlabs@vmware.com>"]
edition = "2021"
repository = 'https://github.com/deislabs/containerd-wasm-shims'
license = "Apache-2.0"
homepage = 'https://github.com/deislabs/containerd-wasm-shims'
description = """
Containerd shim for running Wasm Workers Server workloads.
"""

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
containerd-shim = "0.4.0"
containerd-shim-wasm = { git = "https://github.com/containerd/runwasi", rev = "7850da82a86286f6fcf21e1c93390572ed73592d", features = ["cgroupsv2"]}
wws-config = { git = "https://github.com/vmware-labs/wasm-workers-server", tag = "v1.4.0" }
wws-server = { git = "https://github.com/vmware-labs/wasm-workers-server", tag = "v1.4.0" }
wws-router = { git = "https://github.com/vmware-labs/wasm-workers-server", tag = "v1.4.0" }
log = "0.4"
tokio = { version = "1", features = [ "full" ] }
tokio-util = { version = "0.7", features = [ "codec" ]}
chrono = "0.4"
libcontainer = { version = "0.1", features = ["v2"], default-features = false }
oci-spec = "0.6.2"
libc = "0.2.147"
nix = "0.26.2"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[target.x86_64-unknown-linux-musl.dependencies]
openssl = { version = "=0.10.48", features = ["vendored"] }

[target.aarch64-unknown-linux-musl.dependencies]
openssl = { version = "=0.10.48", features = ["vendored"] }
