spin_manifest_version = "1"
authors = ["Sven Pfennig <s.pfennig@reply.de>"]
description = "Example application to use Dapr with Spin"
name = "spin-dapr"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "spin-dapr"
source = "target/wasm32-wasi/release/spin_dapr.wasm"
allowed_http_hosts = []
[component.trigger]
route = "/..."

[component.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]
