name: 'Build and push Docker images'
on:
  workflow_call:
    inputs:
      test:
        description: 'Is this a test run?'
        type: boolean
        required: true
jobs:
  build_and_push:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - imageName: examples/spin-rust-hello
            context: images/spin
          - imageName: examples/spin-dotnet-hello
            context: images/spin_dotnet
          - imageName: examples/slight-rust-hello
            context: images/slight
          - imageName: examples/wws-js-hello
            context: images/wws
          - imageName: examples/spin-inbound-redis
            context: images/spin-inbound-redis
          - imageName: examples/spin-outbound-redis
            context: images/spin-outbound-redis
          - imageName: examples/lunatic-rust-hello
            context: images/lunatic
          - imageName: examples/lunatic-spawn
            context: images/lunatic-spawn
          - imageName: examples/lunatic-submillisecond
            context: images/lunatic-submillisecond
    steps:
      - uses: actions/checkout@v3
      - name: Set RELEASE_VERSION ENV var
        run: echo "RELEASE_VERSION=${GITHUB_REF:10}" >> $GITHUB_ENV
      - name: lowercase the runner OS name
        shell: bash
        run: |
          OS=$(echo "${{ runner.os }}" | tr '[:upper:]' '[:lower:]')
          echo "RUNNER_OS=$OS" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: setup buildx
        uses: docker/setup-buildx-action@v2
      - name: login to GitHub container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: test
        uses: docker/build-push-action@v4
        if: ${{ inputs.test }}
        with:
          context: ${{ matrix.image.context }}
          load: true
          tags: containerd-wasm-shims${{ matrix.image.imageName }}:test
          platforms: wasi/wasm
      - name: build and push
        # we use v3 here because we can't push wasi/wasm images with v4
        # see https://github.com/deislabs/containerd-wasm-shims/issues/154#issuecomment-1726030749
        uses: docker/build-push-action@v3
        if: ${{ !inputs.test }}
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/${{ matrix.image.imageName }}:${{ env.RELEASE_VERSION }}
            ghcr.io/${{ github.repository }}/${{ matrix.image.imageName }}:latest
          context: ${{ matrix.image.context }}
          platforms: wasi/wasm
